name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: blob:none
    - uses: actions/setup-python@v4
      with:
        cache: pip
    - run: pip install -e .[test]
    - run: pytest --color=yes -vv