name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  JUPYTER_PLATFORM_DIRS: '1'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: blob:none
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: pip
    - run: pip install -e .[test,jupyter]
    - uses: pavelzw/pytest-action@v2
      with:
        custom-arguments: --color=yes
        click-to-expand: false
        verbose: true
        job-summary: true
        emoji: false
